In [1]:
# 以下のライブラリを使うので、あらかじめ読み込んでおいてください
import numpy as np
import numpy.random as random
import scipy as sp

# 可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

# 小数第3位まで表示
%precision 3

'%.3f'

In [3]:
# データの準備
# 等間隔の数字
sample_array = np.arange(10)
print('sample_array:',sample_array)

sample_array: [0 1 2 3 4 5 6 7 8 9]


In [4]:
# 元のデータ
print(sample_array)

# 前から数字を5つ取得して、sample_array_sliceに入れる（スライス）
sample_array_slice = sample_array[0:5]
print(sample_array_slice)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [6]:
# sample_array_sliceの3文字目までは、10で置換
sample_array_slice[0:3] = 10
print(sample_array_slice)

# スライスの変更はオリジナルのリストの要素も変更されていることに注意
print(sample_array)

[10 10 10  3  4]
[10 10 10  3  4  5  6  7  8  9]


In [8]:
# copyして別のobjectを作成
sample_array_copy = np.array(sample_array)
print(sample_array_copy)

sample_array_copy[0:3] = 20
print(sample_array_copy)

# 元のリストの要素は変更されていない
print(sample_array)

[10 10 10  3  4  5  6  7  8  9]
[20 20 20  3  4  5  6  7  8  9]
[10 10 10  3  4  5  6  7  8  9]


In [9]:
# データの準備
sample_names = np.array(['a','b','c', 'd ,a'])
random.seed(0)
data = random.randn(5,5)

print(sample_names)
print(data)

['a' 'b' 'c' 'd ,a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [ ]:
# データの準備
sample_names = np.array(['a','b','c','d','a'])
random.seed(0)
data = random.randn(5,5)

print(sample_names)
print(data)

In [10]:
sample_names == 'a'

array([ True, False, False, False])

In [15]:
data[sample_names == 'a']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [16]:
# 条件制御のためのブールの配列を作成
cond_data = np.array([True,True,False,False,True])

# 配列x_arrayを作成
x_array=np.array([1,2,3,4,5])

# 配列y_arrayを作成
y_array=np.array([100,200,300,400,500])

# 条件制御実施
print(np.where(cond_data,x_array,y_array))

[  1   2 300 400   5]


In [ ]:
#練習問題　5-1
#以下に示すsample_namesとdataという2つの配列があるとします。
#ブールインデックス参照をつかって、dataから、sample_namesのbに該当するデータを抽出してください。

# データの準備
sample_names = np.array(['a','b','c','d','a'])
random.seed(0)
data = random.randn(5,5)

print(sample_names)
print(data)

In [17]:
data[sample_names == 'b']

array([[-0.977,  0.95 , -0.151, -0.103,  0.411]])

In [18]:
#<練習問題 5-2>
#<練習問題 5-1>で使ったデータsample_namesとdataを使って、dataから、sample_namesのc以外に該当するデータを抽出してください。

data[sample_names !='c']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-0.977,  0.95 , -0.151, -0.103,  0.411],
       [ 0.334,  1.494, -0.205,  0.313, -0.854],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [23]:
#<練習問題 5-3>
#次のx_array、y_arrayがあるとき、Numpyのwhereを用いて条件制御し、3番目と4番目はx_arrayから、1番目、2番目、5番目はy_arrayから、それぞれ値を取り出したデータを生成してください。

x_array= np.array([1,2,3,4,5])
y_array= np.array([6,7,8,9,10])

cond_data = np.array([False,False,True,True,False])
print(np.where(cond_data,x_array,y_array))

[ 6  7  3  4 10]


In [24]:
cond_data = np.array([True,True,False,False,True])

# cond_dataを表示
print(cond_data)

#重複削除
print(np.unique(cond_data))

[ True  True False False  True]
[False  True]


In [25]:
# ユニバーサル関数
sample_data = np.arange(10)
print('元のデータ：', sample_data)
print('すべての要素の平方根：',np.sqrt(sample_data))
print('すべての要素のネイピア指数関数：',np.exp(sample_data))

[ True  True False False  True]
[False  True]


In [27]:
# arangeで9つの要素を持つ配列を生成。reshapeで3行3列の行列に再形成
sample_multi_array_data1 = np.arange(9).reshape(3,3)

print(sample_multi_array_data1)

print('最小値:',sample_multi_array_data1.min())
print('最大値:',sample_multi_array_data1.max())
print('平均:',sample_multi_array_data1.mean())
print('合計:',sample_multi_array_data1.sum())

# 行列を指定して合計値を求める
print('行の合計:',sample_multi_array_data1.sum(axis=1))
print('列の合計:',sample_multi_array_data1.sum(axis=0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
最小値: 0
最大値: 8
平均: 4.0
合計: 36
行の合計: [ 3 12 21]
列の合計: [ 9 12 15]


In [28]:
# 真偽値の配列関数
cond_data = np.array([True,True,False,False,True])

print('Trueが少なくとも1つあるかどうか:',cond_data.any())
print('すべてTrueかどうか:',cond_data.all())

Trueが少なくとも1つあるかどうか: True
すべてTrueかどうか: False


In [ ]:
# 真偽値の配列関数
cond_data = np.array([True,True,False,False,True])

print('Trueが少なくとも１つあるかどうか:',cond_data.any())
print('すべてTrueかどうか:',cond_data.all())

In [29]:
sample_multi_array_data1 = np.arange(9).reshape(3,3)
print(sample_multi_array_data1)
print('5より大きい数字がいくつあるか:',(sample_multi_array_data1>5).sum())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
5より大きい数字がいくつあるか: 3


In [31]:
# 行列計算
sample_multi_array_data1 = np.arange(9).reshape(3,3)
print(sample_multi_array_data1)

print('対角成分:',np.diag(sample_multi_array_data1))
print('対角成分の和:',np.trace(sample_multi_array_data1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
対角成分: [0 4 8]
対角成分の和: 12


In [ ]:
# 行列計算
sample_multi_array_data1 = np.arange(9).reshape(3,3)
print(sample_multi_array_data1)

print('対角成分:',np.diag(sample_multi_array_data1))
print('対角成分の和:',np.trace(sample_multi_array_data1))

In [32]:
#<練習問題 5-4>
#以下のデータに対して、すべての要素の平方根を計算した行列を表示してください。
sample_multi_array_data2 = np.arange(16).reshape(4,4)
sample_multi_array_data2 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
#<練習問題 5-4>
#以下のデータに対して、すべての要素の平方根を計算した行列を表示してください。

sample_multi_array_data2 = np.arange(16).reshape(4,4)
print(sample_multi_array_data2)
print(sample_multi_array_data2**0.5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0.    1.    1.414 1.732]
 [2.    2.236 2.449 2.646]
 [2.828 3.    3.162 3.317]
 [3.464 3.606 3.742 3.873]]


In [36]:
#<練習問題 5-5>
#<練習問題 5-4>のデータsample_multi_array_data2の最大値、最小値、合計値、平均値を求めてください。

print(sample_multi_array_data2.max())
print(sample_multi_array_data2.min())
print(sample_multi_array_data2.sum())
print(sample_multi_array_data2.mean())

15
0
120
7.5


In [35]:
#<練習問題 5-6>
#<練習問題 5-4>のデータsample_multi_array_data2の対角成分の和を求めてください。

np.trace(sample_multi_array_data2)

30

In [ ]:
# データの準備
sample_array = np.arange(10)
sample_array

In [ ]:
# 再形成
sample_array2 = sample_array.reshape(2,5)
sample_array2

In [ ]:
sample_array2.reshape(5,2)

In [37]:
#　データの準備
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])
print(sample_array3)
print(sample_array4)

# 行方向に結合。パラメータのaxisに0を指定
np.concatenate([sample_array3,sample_array4],axis=0)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])